// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llohnziefwmruguqoofl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsb2huemllZndtcnVndXFvb2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjEwNTEsImV4cCI6MjA3MDMzNzA1MX0.8eTm5k4of-ZpT6MUnfNsRxjK0mN4AhZKPzszpFCVJV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});